__version__ = '0.1.0.dev'
__description__ = 'A remote client for UData administrative tasks'
__author__ = 'Open Data Team'
__email__ = 'opendatateam@data.gouv.fr'
__url__ = 'https://github.com/opendatateam/udata-cli'
